export const AUTH_ACTION = "AUTH_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const INVALIDATE_AUTH_ACTION = "INVALIDATE_AUTH_ACTION";
export const WHO_AM_I_ACTION = "WHO_AM_I_ACTION"
